name: Test things on pushes

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We currently only support up to python 3.11 
        # because aiohttp does not support 3.12 as of yet.
        # 3.7 because Google Colab uses 3.7 by default.
        python-version: [3.7, 3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/setup.py
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,types]
      - name: Lint with mypy
        run: |
          mypy aleph_alpha_client
          mypy --ignore-missing-imports tests
      - name: Run tests
        run: |
          pytest
        env:
          TEST_API_URL: https://api.aleph-alpha.com
          TEST_TOKEN: ${{ secrets.AA_API_TOKEN }}
