name: Test things on pushes

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: |
            **/setup.py
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,types]
      - name: Lint with mypy
        run: |
          mypy aleph_alpha_client
          mypy --ignore-missing-imports tests
      - name: Run tests
        run: |
          pytest
        env:
          TEST_API_URL: https://api.aleph-alpha.com
          TEST_TOKEN: ${{ secrets.AA_API_TOKEN }}
          TEST_MODEL: luminous-base
          TEST_CHECKPOINT: ${{ secrets.TEST_CHECKPOINT }}
          TEST_CHECKPOINT_QA: ${{ secrets.TEST_CHECKPOINT_QA }}
          TEST_CHECKPOINT_SUMMARIZATION: ${{ secrets.TEST_CHECKPOINT_SUMMARIZATION }}
