name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install deps
        run: poetry install
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
